// Frontend (React + Vite + Storybook) ESLint flat config.
// Layers browser/React/MDX config on top of the shared monorepo base.
// See https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import storybook from 'eslint-plugin-storybook'
import * as mdx from 'eslint-plugin-mdx'
import tseslint from 'typescript-eslint'

import { baseConfig, sharedIgnores } from '../eslint.config.mjs'

export default tseslint.config(
  // `routeTree.gen.ts` is generated by TanStack Router and already self-disables lint;
  // ignore it outright so it is never parsed.
  { ignores: [...sharedIgnores, 'src/routeTree.gen.ts'] },

  // Shared JS + TypeScript recommended rules, scoped to real source files.
  ...baseConfig,
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
    rules: {
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
    },
  },
  ...storybook.configs['flat/recommended'],

  // MDX docs (Storybook stories/pages). `mdx.flat` supplies the real MDX parser and
  // processor for **/*.{md,mdx}; spreading it last lets it override the TypeScript
  // parser the base config would otherwise apply to these files.
  mdx.flat,
  mdx.flatCodeBlocks,
)
