/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/create-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a user account
         * @description Registers a new user under the given organization. `email` must be unique - a request reusing an existing address is rejected with 409. `password` is received as plaintext over TLS and hashed server-side (argon2id) before storage; it is never echoed back in a response. On success a signed, httpOnly session cookie is set, logging the new user in immediately.
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email and password
         * @description Verifies `email` and `password` against the stored argon2id hash and returns the matching user. On success a signed, httpOnly session cookie is set - see the `security` TODO at the top of this document for why routes do not yet require it.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Clears the session cookie. Succeeds even when the caller has no session - there is nothing server-side to invalidate, since sessions are stateless signed cookies (see src/utils/userSessions.ts).
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the signed-in user
         * @description Returns the user identified by the session cookie. The `id` is taken from the signed cookie payload and never from the request, so a caller can only ever read their own profile. A cookie that is missing, malformed or expired is answered with 401; a well-formed session whose user no longer exists is answered with 404.
         */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List events overlapping a time window
         * @description Returns events whose `[startsAt, endsAt]` interval overlaps the requested window, ordered by `startsAt`. `startDate` defaults to the current time and `endDate` is unbounded when omitted. `endDate` must be later than `startDate` - that relationship cannot be expressed in the schema, so the server enforces it and answers an inverted window with 400.
         *
         *     Overlap, not containment: an event that began before the window and is still running is in it.
         *
         *     The response is deliberately unpaginated and uncapped: the time window is what bounds the result set.
         */
        get: operations["listEvents"];
        put?: never;
        /**
         * Create an event
         * @description Creates an event owned by the signed-in user. `ownerId` is taken from the session cookie and is rejected if sent in the body, so a caller can only ever publish as themselves; `organizationId` follows from that owner.
         *
         *     `endsAt` must be later than `startsAt`. JSON Schema cannot compare two fields, so the server enforces it and rejects an inverted interval with 400 - mirroring the `ends_at > starts_at` CHECK in schema.dbml.
         */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/events/${string}`]: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        /** Get a single event */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all participating organizations
         * @description Returns every participating organization, ordered by `name`. Like `/events`, the response is unpaginated - the directory is bounded by the number of participating organizations, which is small.
         */
        get: operations["listOrganizations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/organizations/${string}`]: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        /** Get a single organization */
        get: operations["getOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: date-time */
        Timestamp: string;
        /** @description Identifier of an organization (an `organizations` row). */
        OrganizationId: number;
        /** @description Identifier of a user. */
        UserId: number;
        /** @description Identifier of an event. */
        EventId: number;
        /**
         * @description A category an organization can be listed under. Mirrors the `org_tags` enum in db/schema.dbml; SQLite has no enum type, so the same values are held by the `IN (...)` CHECK on `organizations_tags.tag`.
         * @enum {string}
         */
        OrganizationTag: "Advocacy" | "Civic" | "Community" | "Culture" | "Education" | "Equity" | "Indigenous" | "Makers" | "Policy" | "Research" | "Seniors" | "Settlement" | "Tech" | "Volunteer" | "Youth";
        /** @description A participating organization. Mirrors the `organizations` table. */
        Organization: {
            readonly id: components["schemas"]["OrganizationId"];
            /** @description The `pattern` matches the `length(trim(name)) > 0` CHECK in schema.dbml. */
            name: string;
            /**
             * Format: uri-reference
             * @description Server-relative path to the logo image, e.g. `./public/organization_logos/example.jpg` - not an absolute URL.
             */
            logo?: string | null;
            blurb?: string | null;
            /**
             * Format: email
             * @description SQLite stores this unconstrained (see the note at the top of schema.prisma). `pattern` mirrors the DBML CHECK and `format` applies ajv's own rule - neither subsumes the other, so both are declared and a value has to satisfy both.
             */
            contact?: string | null;
            /**
             * Format: uri
             * @description Restricted to http(s), mirroring the CHECK in schema.dbml. See the case-sensitivity note on `Event.registrationLink`.
             */
            website?: string | null;
            /** @description The organization's categories. An organization with no tags yields an empty array. */
            tags?: components["schemas"]["OrganizationTag"][];
        };
        /** @description The client-supplied half of a user. Mirrors the `users` table. */
        UserCore: {
            /** @description The `pattern` matches the `length(trim(fullname)) > 0` CHECK in schema.dbml. */
            fullname: string;
            /**
             * Format: email
             * @description Must be unique across users; a request reusing an existing address is rejected with 409. `pattern` mirrors the DBML CHECK and `format` applies ajv's own rule - see the note on `Organization.contact`.
             */
            email: string;
            organizationId: components["schemas"]["OrganizationId"];
        };
        /** @description Unknown properties are rejected rather than ignored, so a request that tries to smuggle in `id` or `createdAt` (or any other server-assigned field) fails validation instead of being silently dropped. */
        UserCreate: components["schemas"]["UserCore"] & {
            /** @description Plaintext password, sent once over TLS and hashed (argon2id) server-side before storage. Mirrors the `length(password) > 0` CHECK in schema.dbml, with a minimum length enforced at the application layer. */
            password: string;
        };
        User: components["schemas"]["UserCore"] & {
            readonly id: components["schemas"]["UserId"];
            readonly createdAt: components["schemas"]["Timestamp"];
        };
        /** @description Unknown properties are rejected rather than ignored, so a request that tries to smuggle in extra fields fails validation instead of being silently dropped. */
        UserLogin: {
            /** Format: email */
            email: string;
            /** @description Plaintext password, sent once over TLS and checked against the stored argon2id hash. */
            password: string;
        };
        /** @description The client-supplied half of an event. Everything the server assigns - `id`, `ownerId`, `organizationId`, `createdAt` - lives on `Event` instead, so none of it can be supplied on a create. */
        EventCore: {
            /** @description The `pattern` requires at least one non-whitespace character, matching the `length(trim(title)) > 0` CHECK in schema.dbml - `minLength` alone would admit `"   "`. */
            title: string;
            startsAt: components["schemas"]["Timestamp"];
            /** @description Must be later than `startsAt`. Enforced server-side rather than in the schema, since JSON Schema cannot compare two fields. */
            endsAt: components["schemas"]["Timestamp"];
            location?: string | null;
            description?: string | null;
            /**
             * Format: uri-reference
             * @description Server-relative path to the event image, e.g. `./public/event_images/example.jpg` - not an absolute URL.
             */
            thumbnail?: string | null;
            /**
             * Format: uri
             * @description Restricted to http(s), mirroring the CHECK in schema.dbml. That CHECK is case-insensitive (`~*`) while JSON Schema patterns are not, so an uppercase scheme is rejected here though the database would accept it - normalise the scheme before insert.
             */
            registrationLink?: string | null;
            /**
             * Format: email
             * @description `pattern` mirrors the DBML CHECK and `format` applies ajv's own rule; see the note on `Organization.contact`.
             */
            volunteerContact?: string | null;
        };
        /** @description Unknown properties are rejected rather than ignored, so a request that tries to smuggle in `ownerId` (or any other server-assigned field) fails validation instead of being silently dropped. */
        EventCreate: components["schemas"]["EventCore"];
        Event: components["schemas"]["EventCore"] & {
            readonly id: components["schemas"]["EventId"];
            /** @description The user who owns the event, resolved from the authenticated caller at creation time - never from the request body. */
            readonly ownerId: components["schemas"]["UserId"];
            /**
             * @description The owning user's organization, resolved server-side by following `ownerId` - the `events` table has no organization column of its own. Clients match this against the organizations they hold rather than fetching per event; it is also what the `organizationId` query parameter filters on.
             *
             *     Because the link is derived rather than stored, it tracks the owner's *current* organization - if a user moves organizations, their past events move with them. Storing the publishing organization on the event instead would be a schema change.
             */
            readonly organizationId: components["schemas"]["OrganizationId"];
            readonly createdAt: components["schemas"]["Timestamp"];
        };
        /** @description RFC 9457 problem details. */
        Problem: {
            /**
             * Format: uri
             * @default about:blank
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
        };
        /** @description A `Problem` carrying the RFC 9457 `errors` extension. `errors` is present whenever the failure can be attributed to specific fields, and absent when it cannot - a body that is not parseable as JSON, for instance, has no field to point at. */
        ValidationProblem: components["schemas"]["Problem"] & {
            errors?: {
                /** @description JSON Pointer to the offending value, prefixed with the part of the request it came from - e.g. `/body/startsAt`, `/query/startDate`, `/params/eventId`. */
                pointer: string;
                detail: string;
            }[];
        };
    };
    responses: {
        /** @description Error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request failed validation - body, query, or path parameters. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
        /** @description The request body was sent as something other than `application/json`. */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request conflicts with the current state of the resource - e.g. an `email` that is already registered to another user. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The caller could not be authenticated - either the supplied email and password did not match an existing account, or the session cookie was missing, malformed or expired. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Start of the time window. Defaults to the current time when omitted. */
        StartDate: components["schemas"]["Timestamp"];
        /** @description End of the time window. Unbounded when omitted. Must be later than `startDate`. */
        EndDate: components["schemas"]["Timestamp"];
        /** @description Only return events published under this organization. */
        OrganizationIdFilter: components["schemas"]["OrganizationId"];
        EventId: components["schemas"]["EventId"];
        OrganizationId: components["schemas"]["OrganizationId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description URI of the newly created user. */
                    Location: string;
                    /** @description Signed, httpOnly session cookie (see src/utils/userSessions.ts). */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["Conflict"];
            415: components["responses"]["UnsupportedMediaType"];
            default: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    /** @description Signed, httpOnly session cookie (see src/utils/userSessions.ts). */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            415: components["responses"]["UnsupportedMediaType"];
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    /** @description Session cookie cleared. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                /** @description Start of the time window. Defaults to the current time when omitted. */
                startDate?: components["parameters"]["StartDate"];
                /** @description End of the time window. Unbounded when omitted. Must be later than `startDate`. */
                endDate?: components["parameters"]["EndDate"];
                /** @description Only return events published under this organization. */
                organizationId?: components["parameters"]["OrganizationIdFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            400: components["responses"]["ValidationError"];
            default: components["responses"]["Problem"];
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description URI of the newly created event. */
                    Location: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            415: components["responses"]["UnsupportedMediaType"];
            default: components["responses"]["Problem"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of organizations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"][];
                };
            };
            400: components["responses"]["ValidationError"];
            default: components["responses"]["Problem"];
        };
    };
    getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
}
