// import { C } from "../../styles/colors";

// TODO: refactor this w/ CSS
// reference: https://blog.logrocket.com/building-reusable-react-components-using-tailwind-css/#testing-badge-component
export enum ButtonVariant {
  PRIMARY,
  GHOST,
  SUBTLE,
  DANGER
}

const VARIANT_MAPS: Record<ButtonVariant, string> = {
  [ButtonVariant.PRIMARY]: "bg-action-primary-bg text-action-primary-fg active:opacity-80",
  [ButtonVariant.GHOST]: "bg-transparent outline-border-strong text-text-primary",
  [ButtonVariant.SUBTLE]: "bg-bg-subtle text-text-primary",
  [ButtonVariant.DANGER]: "bg-action-danger-bg text-action-danger-fg"
}
//   primary: { background: C.accent, color: C.white, borderColor: C.accent },
//   ghost: { background: "transparent", color: C.accent, borderColor: C.line },
//   subtle: { background: C.accentSoft, color: C.accent, borderColor: "transparent" },
//   danger: { background: "transparent", color: C.danger, borderColor: "rgba(178,58,72,0.3)"},
//   link: { background: "none", border: "none", color: C.muted, fontSize: 12.5, cursor: "pointer", 
//   // fontFamily: "'Public Sans', sans-serif", 
//   textDecoration: "underline", padding: 0 },
// } as const;

// type ButtonVariant = keyof typeof variants;

type ButtonProps = {
  /** Variations on button styling */
  variant: ButtonVariant;
  /** Label for the button, used for accessibility and default display text unless otherwise specified */
  label: string;
  /** custom display text for the button if not using the label */
  displayText?: string;
  /** what do when button */
  onClick: () => void;
  children?: React.ReactElement[];
};

/** Generic button component */
export default function Button({ 
  variant = ButtonVariant.PRIMARY,
  label,
  onClick,
  children,
 }: ButtonProps) {
  // removed class generated by Figma - hover:shadow-[0px_2px_6px_0px_rgba(2,7,3,0.2)] replaced with Claude-generated animation classes
  const buttonStyles = "cf-press font-sans font-semibold text-[14px] px-[14px] py-2 rounded-sm cursor-pointer border leading-[1.1] tracking-[0.1px]";
  const finalButtonStyles = `${buttonStyles} ${VARIANT_MAPS[variant]}`
  return (
    <button 
      aria-label={label}
      onClick={onClick}
      className={`${finalButtonStyles} cf-card-hover`}
    >
      {label} {children}
    </button>
  );
}