import type { ButtonVariant } from "../../types/variants";

// reference: https://blog.logrocket.com/building-reusable-react-components-using-tailwind-css/#testing-badge-component
const VARIANT_MAPS: Record<ButtonVariant, string> = {
  "primary": "bg-action-primary-bg text-action-primary-fg active:opacity-80",
  "ghost": "bg-transparent outline-border-strong text-text-primary",
  "subtle": "bg-bg-subtle text-text-primary",
  "danger": "bg-action-danger-bg text-action-danger-fg",
  "link": "bg-transparent text-bg-subtle underline"
}

type ButtonProps = {
  /** Variations on button styling */
  variant?: ButtonVariant;
  /** Label for the button, used for accessibility and default display text unless otherwise specified */
  label: string;
  /** what do when button */
  onClick: () => void;
  /** child elements; for a button, usually just the display text */
  children?: React.ReactElement[] | string;
  /** additional Tailwind classes */
  styles?: string;
};

/** Generic button component */
export default function Button({ 
  variant = "primary",
  label,
  onClick,
  children,
  styles,
 }: ButtonProps) {
  // removed class generated by Figma - hover:shadow-[0px_2px_6px_0px_rgba(2,7,3,0.2)] replaced with Claude-generated animation classes
  const buttonStyles = "cf-press font-sans font-semibold text-[14px] px-[14px] py-2 rounded-sm cursor-pointer border leading-[1.1] tracking-[0.1px]";
  const finalButtonStyles = `${buttonStyles} ${VARIANT_MAPS[variant]} ${styles || ''}`
  return (
    <button 
      aria-label={label}
      onClick={onClick}
      className={`${finalButtonStyles} cf-card-hover`}
    >
      {label} {children}
    </button>
  );
}